name: markify

services:
  app:
    environment:
      - NODE_DEBUG=https,http,net
      - NODE_OPTIONS=--trace-warnings --trace-deprecation
    image: ${DOCKER_USERNAME}/markify:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_PUBLIC_API_DOCS_ENABLED: ${NEXT_PUBLIC_API_DOCS_ENABLED:-true}
        NEXT_PUBLIC_BETTER_AUTH_URL: ${NEXT_PUBLIC_BETTER_AUTH_URL}
    env_file:
      - .env.production
    ports:
      - "3024:3024"
    restart: unless-stopped
    extra_hosts:
      - "e2526-wads-b4bc-03.csbihub.id:host-gateway"

  db-schema-sync:
    profiles: ["migrate"]
    build:
      context: .
      dockerfile: Dockerfile
      target: migrator
    env_file:
      - .env.production
    restart: "no"