"use client";

import Link from "next/link";
import { Eye, Trash2, Users, Loader2, KeyRound, GraduationCap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ClassSummary } from "@/services/classes/types";
import { getAccentColor } from "@/lib/accent-color";
import { AlertDialog, AlertDialogAction, AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

interface LecturerClassCardProps {
    cls: ClassSummary;
    index?: number;
    onDelete?: (cls: ClassSummary) => void;
    deleting?: boolean;
}

export function LecturerClassCard({ cls, onDelete, deleting = false }: LecturerClassCardProps) {
    const color = getAccentColor(`${cls.courseCode}-${cls.academicYear}`);

    return (
            <Card className="group relative overflow-hidden hover:shadow-md transition-shadow duration-200">
                <div className="flex items-stretch">
                    {/* left color accent */}
                    <div className="absolute left-0 top-0 bottom-0 w-1.5" style={{ backgroundColor: `hsl(${color})` }} />

                    <div className="flex-1 flex flex-col sm:flex-row sm:items-center gap-4 px-4 sm:px-5 ml-3 sm:ml-0">
                        {/* icon and identity */}
                        <div className="flex items-start gap-4 flex-1 min-w-0">
                            <div className="hidden sm:flex w-11 h-11 rounded-md items-center justify-center my-auto shrink-0 mx-1.5" style={{ backgroundColor: `hsl(${color} / 0.12)` }}>
                                <GraduationCap className="w-5 h-5" style={{ color: `hsl(${color})` }} />
                            </div>

                            <div className="min-w-0 flex-1">
                                <div className="flex items-center gap-2 mb-1 flex-wrap">
                                    <Badge variant="secondary" className="text-xs font-mono">
                                        {cls.courseCode}
                                    </Badge>
                                    <Badge variant="outline" className="text-xs">
                                        {cls.classCode}
                                    </Badge>
                                    <Badge variant="outline" className="text-xs text-muted-foreground">
                                        {cls.academicYear}
                                    </Badge>
                                </div>
                                <h3 className="text-base sm:text-lg font-semibold text-foreground leading-snug truncate">
                                    {cls.courseName}
                                </h3>
                                <div className="grid grid-flow-col auto-cols-max mt-1 text-sm text-muted-foreground gap-x-5 sm:gap-x-8">
                                    <span className="flex items-center gap-1.5">
                                        <Users className="w-3.5 h-3.5" /> {cls.students} students
                                    </span>
                                    <span className="flex items-center gap-1.5">
                                        <TooltipProvider>
                                            <Tooltip>
                                                <TooltipTrigger asChild>
                                                    <KeyRound className="w-3.5 h-3.5" /> 
                                                </TooltipTrigger>
                                                <TooltipContent side="top" className="max-w-3xs text-xs">
                                                    Unique enrollment key generated by Markify. Share with students to join this class.
                                                </TooltipContent>
                                            </Tooltip>
                                        </TooltipProvider>
                                        {cls.enrollmentKey}
                                    </span>
                                </div>
                            </div>
                        </div>

                        {/* actions */}
                        <div className="flex items-center gap-2 sm:shrink-0 self-end sm:self-auto mt-6 sm:mt-0">
                            <Link href={`/dashboard/lecturer/class/${cls.classId}`} className="flex-1 sm:flex-none">
                                <Button variant="default" size="sm" className="w-50 sm:w-full gap-1.5 cursor-pointer">
                                    <Eye className="w-3.5 h-3.5" />
                                    View Class
                                </Button>
                            </Link>
                            {onDelete && (
                                deleting
                                    ? <Loader2 className="w-3.5 h-3.5 animate-spin" />
                                    : <AlertDialog>
                                        <AlertDialogTrigger asChild>
                                            <Button variant="ghost" size="sm" className="text-destructive hover:text-destructive hover:bg-destructive/10 cursor-pointer">
                                                <Trash2 className="w-3.5 h-3.5" />
                                            </Button>
                                        </AlertDialogTrigger>
                                        <AlertDialogContent className="max-w-[60vw] sm:max-w-sm">
                                            <AlertDialogHeader className="select-none">
                                                <AlertDialogTitle>Delete Class</AlertDialogTitle>
                                                <AlertDialogDescription className="my-2">
                                                    Are you sure you want to delete class <span className="font-medium text-foreground">{cls.classCode} {cls.courseName} ({cls.academicYear})</span>? All data related to this class will be deleted. This action cannot be undone.
                                                </AlertDialogDescription>
                                            </AlertDialogHeader>
                                            <AlertDialogFooter>
                                                <AlertDialogCancel className="cursor-pointer">Cancel</AlertDialogCancel>
                                                <AlertDialogAction className="cursor-pointer disabled={deleting} bg-destructive! text-destructive-foreground! hover:bg-destructive/90!" onClick={() => onDelete(cls)}>
                                                    Delete Class
                                                </AlertDialogAction>
                                            </AlertDialogFooter>
                                        </AlertDialogContent>
                                    </AlertDialog>
                            )}
                        </div>
                    </div>
                </div>
            </Card>
    );
}